# Generated by Django 4.1 on 2022-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(choices=[('FC', 'First_class'), ('SC', 'Second_class'), ('F', 'fail'), ('D', 'distinction'), ('NA', 'Not_available')], default='NA', max_length=20),
        ),
    ]
