# Generated by Django 4.1 on 2022-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_accounts', '0002_alter_student_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
