# Generated by Django 4.1 on 2022-08-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_accounts', '0004_subject_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(through='student_accounts.Score', to='student_accounts.subject'),
        ),
    ]
