# Generated by Django 4.1 on 2022-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_accounts', '0005_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uploaded_all_subjects',
            field=models.BooleanField(default=False),
        ),
    ]
