# Generated by Django 4.1 on 2022-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_accounts', '0003_alter_student_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PHY', 'physics'), ('CHEM', 'chemistry'), ('BIO', 'biology'), ('CS', 'computer_science'), ('PSY', 'psychology'), ('FIN', 'finance')], max_length=50)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ManyToManyField(to='student_accounts.student')),
            ],
        ),
    ]
