# Generated by Django 4.1 on 2022-08-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_card', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
