# Generated by Django 4.1 on 2022-08-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_accounts', '0003_alter_student_total_score'),
        ('score_card', '0002_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PHY', 'physics'), ('CHEM', 'chemistry'), ('BIO', 'biology'), ('CS', 'computer_science'), ('PSY', 'psychology'), ('FIN', 'finance')], max_length=50)),
                ('student', models.ManyToManyField(through='score_card.Score', to='student_accounts.student')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_card.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'subject')},
        ),
    ]
