# Generated by Django 4.1 on 2022-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_card', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('computer_science', 'computer_science'), ('psychology', 'psychology'), ('finance', 'finance')], max_length=50),
        ),
    ]
