# Generated by Django 4.1 on 2022-08-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_card', '0004_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
